### PR TITLE
Fixed Seadra issue, added browser desktop shortcut compatibility and more

### PR DESCRIPTION
**Pull request by Deses**
Hey! I've been working on some stuff.

I fixed Seadra entry in the pokémon list so it doesn't need "needevo".
Moved some stuff to its own files. Also formated the pokemon list to everyone has its metadata (candy: 0, meta: "", etc).
Moved Bellosom to its correct family.
And added compatibility for that feature Chrome has where you can pin websites to desktop so they behave like an app.

### CODE REVIEW

**Comment by mikeappell** [comment]
Awesome! Never even realized something was in the wrong family, thanks for noticing/fixing. I'll merge this and take a look.

**Comment by mikeappell** [comment]
Yeah, re: Seadra I should be doing slightly different processing on needevo vs. isevo, but I haven't given much thought to that in a while, and it would add some complexity. This definitely works in the interim 👍

**Comment by Deses** [comment]
Just curious: What's the difference betweeen your imports vs my imports?

`const Constants = require('./Constants');`
I've been using these since forever and I wonder if there is any benefit with using these:
`import { Constants } from './Constants';`
Or it is just for consistency's sake, as your comment suggest?

**Comment by mikeappell** [comment]
As far as I know, they're functionally equivalent: one is the 'Node' way of doing it and one is more 'React'ish.

Doing `export`/`export default ...` and then `import xxx from ...`/`import { xxx } ...` is just using ES6 native syntax, and `module.exports` is a Node structure I believe - though I'm much less familiar with Node.

Purely for consistency's sake 😃

**Comment by Deses** [comment]
I see! It's nice to learn something new. :D

**Comment by mikeappell** [comment]
Definitely! Remind me, but have you worked a lot with Node in the past? It's something I'd love to learn more about in my downtime.

I _believe_ that `module` wouldn't be available outside of a Node environment (seem to recall that from the brief Node tutorials I went through), whereas export/import are from [here](http://es6-features.org/#ValueExportImport).

**Comment by Deses** [comment]
Not much experience in node, really! Just React and ECMAScript 6, but following guides and influence from coworkers lead me to use some Node stuff, as you can see.

> I believe that module wouldn't be available outside of a Node environment (seem to recall that from the brief Node tutorials I went through), whereas export/import are from here.

In that case it makes more sense to use export/import than module for React. I'll take into account the next time. 😄

**Pull request merged**
